services:
  # Banco Vetorial Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    ports:
      - "6333:6333"
    volumes:
      # Usando volume nomeado para evitar erro de permissão no Windows
      - qdrant_data:/qdrant/storage
    networks:
      - rag_network

  # Serviço da aplicação Python
  backend:
    build: .
    container_name: rag-backend
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - qdrant
    networks:
      - rag_network

volumes:
  qdrant_data:

networks:
  rag_network:
    driver: bridge